---
abstract: "Easy access to Shutterstock's public API"
author:
  - 'Brian Phillips <bphillips@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::MockModule: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Shutterstock
requires:
  Carp: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Moo: 1
  Moo::Role: 0
  REST::Client: 0
  Sub::Exporter: 0
  overload: 0
  strict: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/brianphillips/WebService-Shutterstock/issues
  homepage: http://search.cpan.org/dist/WebService-Shutterstock/
  repository: git://github.com/brianphillips/WebService-Shutterstock.git
version: 0.005
